
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Adamantina',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Adolfo',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ('Aguaí',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ('Águas da Prata',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Águas de Lindóia',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Águas de Santa Bárbara',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Águas de São Pedro',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Agudos',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Alambari',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Alfredo Marcondes',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Altair',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Altinópolis',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Alto Alegre',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Alumínio',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Álvares Florence',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Santo André',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Santos',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'São Paulo',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ('Urânia',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ('Uru',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ('Urupês',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Valentim Gentil',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ('Valinhos',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Valparaíso',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Vargem',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Vargem Grande do Sul',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Vargem Grande Paulista',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Várzea Paulista',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Vera Cruz',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Vinhedo',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Viradouro',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Vista Alegre do Alto',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Vitória Brasil',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Votorantim',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ('Votuporanga',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Zacarias',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ( 'Chavantes',22);
INSERT INTO tb_cidade (nome,id_uf) VALUES ('Estiva Gerbi',22);
